# -*- coding: utf-8 -*-
"""CriacaoAplicativosDataWebPythonBibliotecaStreamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLP6v-4xsNMu4vdIB-q_PScZz5F02omo
"""

# Importando as Bibliotecas
import streamlit as st

st.image("calc-guide.png", use_column_width=True)
st.title("Resultado:")
st.sidebar.title("Calculadora de ano de nascimento")
idade = st.sidebar.text_input("Qual idade você completará ou completou este ano?")
opcao = st.sidebar.checkbox('Já fiz aniverário esse ano', value=False)
botao = st.sidebar.button("Clique aqui para realizar o cálculo")

if botao:
  if opcao: ano = 2023 - int(idade)
  else: ano = 2023 - int(idade)-1
  st.write(f"Você nasceu no ano de: **{ano}**")